name: nb_conda
channels:
  - anaconda-nb-extensions/label/dev
  - anaconda-nb-extensions
  - javascript
dependencies:
  - python
  - nb_conda_kernels
  - nose
  - mock
  - coverage
  - flake8
  - nodejs
  - requests
