package:
  name: nb_conda
  version: "0.1.0"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

requirements:
  build:
    - python
  run:
    - python
    - nbwrapper
    - nbsetuptools

test:
  requires:
    - mock
    - notebook
    - python
    - requests
    - nose

  commands:
    - nosetests -w ${SRC_DIR}

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/nb_conda
  license: BSD
