package:
  name: nb_conda
  version: "1.0.0"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

requirements:
  build:
    - python
    - notebook >4.1
  run:
    - python
    - notebook >4.1
    - nb_conda_kernels

test:
  requires:
    - mock
    - notebook >4.1
    - python
    - requests
    - nose

source:
  git_url: ../

about:
  home: https://github.com/Anaconda-Server/nb_conda
  license: BSD
